import {
  BUSINESS_DEVELOPMENT,
  FINANCE_ROUTE,
  HUMAN_RESOURCES_ROUTE,
  LEGAL_AND_LAW_ROUTE,
  MANAGEMENT_ROUTE,
  MARKETING_ROUTE,
  PRODUCT_ROUTE,
  TECHNOLOGY_ROUTE,
} from "../utils/consts";

export const allTopiks = [
  {
    Marketing: [
      "Market Research",
      "Competitive Analysis",
      "Key Marketing Indicators",
      "Marketing Plans",
      "Marketing Strategies",
      "The Neuroscience of Branding",
      "Marketing Colors Psychology",
      "Behavioral Advertising",
      "Marketing Campaigns",
      "Customer Acquisition Process",
      "Social Media Marketing",
      "Agile Marketing",
      "Marketing A/B Testing",
      "Community Relationships",
      "Marketing Anticipation and Perfect Timing",
      "(CRM)Customer Relationship Manager",
      "Brand Loyalty Guide",
    ],
    link: MARKETING_ROUTE,
  },
  {
    Financial: [
      "P&L Statements",
      "Cash flow Statements",
      "Balance Sheets",
      "Fundraising Capital Options",
      "Valuation Process",
      "Valuation Methods",
      "Share Vesting",
      "SAFEs and Convertible Notes",
      "EIPs and ESOPs",
      "Fundraising Stages",
      "Venture Capitals in Israel",
      "Private Equity Firms in Israel",
      "Consulting Firms",
      "Hedge Funds",
      "Concepts in Economics",
      "Concepts in Capital Markets",
      "Financial Terms Everyone should know",
      "Investing VS Trading Concepts",
      "Financial Reporting",
    ],
    link: FINANCE_ROUTE,
  },
  {
    Management: [
      "Agile Methodologies",
      "Decision-Making Methods",
      "Time-Management Methods",
      "Risk-Management Methods",
      "Data-Driven Strategies",
      "Key Performance Indicators",
      "Applications for Enterprise Management",
      "The PIVOT Guide",
      "Pitch Deck Presentations",
      "Elevator Pitch for Founders",
      "(ERP)Enterprise Resource Planning",
      "(ERM)Enterprise Risk Management",
      "Storytelling for Founders",
      "(M&A)Merge and Acquisitions",
      "Strategic Planning",
      "Executive Summaries",
      "Management Consulting",
      "Benchmarks and Workflows",
    ],
    link: MANAGEMENT_ROUTE,
  },
  {
    Technology: [
      "Artificial intelligence",
      "Business Automatoins",
      "Blockchan",
    ],
    link: TECHNOLOGY_ROUTE,
  },
  {
    Product: [
      "Product Development Process",
      "Product Strategy",
      "Product Roadmaps",
      "Product Backlogs",
      "Product A/B Testing",
      "Design Sprints",
      "Prototypes and MVPs",
      "Proof of Value",
      "Proof of Concept",
      "Mockups",
      "Pilot Testing",
      "Agile Product Development",
      "APIs Product Management(PM)",
    ],
    link: PRODUCT_ROUTE,
  },
  {
    HumanResourse: [
      "Terminology in HR Management",
      "(ATS)Applicant Tracking System",
      "Recruitment Process",
      "Onboarding",
      "Talent Acquisition",
      "Employee Training&Staffing",
      "Employee Benefits",
    ],
    link: HUMAN_RESOURCES_ROUTE,
  },
  {
    Entrepreneurship: [
      "Steve Jobs",
      "Larry Page",
      "Andrew Carnegie",
      "Ted Turner",
      "Elon Musk",
      "William Henry Gates",
      "Donald J. Trump",
      "Henry Ford",
      "Jensen Huang",
      "Alain Wertheimer",
      "Dan Pena",
      "Warren Buffet",
      "Mark Zuckerberg",
      "Jeff Bezos",
      "Ray Dalio",
      "Mark Cuban",
      "Bill Miller",
      "Michael Burry",
      "Catherine D. Wood",
      "Andy Grove",
      "Richard Branson",
      "Jim Rohn",
      "Napoleon Hill",
      "Hans Wilsdorf",
      "Horacio Pagani",
      "Luis Chevrolet",
      "Christian Dior",
      "Frederick Henry Royce",
      "Bernard Arnault",
      "Marc Benioff",
      "Geoffrey Hinton",
      "Nikola Tesla",
      "William James Sidis",
      "Amnon Shaashua",
      "Ferdinand Porsche",
      "Gautam Adani",
      "Ziv Aviram",
      "Yossi Vardi",
      "Dov Moran",
      "Asaf Rapaport",
      "Yehonatan Shteren",
      "Sam Altman",
      "Adam Neumann",
      "Tedi Sagi",
      "Beny Zeevi",
      "Noam Vaiman",
      "Rachel Grinberg",
      "Shay Agassi",
      "Simcha Shor",
      "Daniel Ek",
      "Martin Lorentzon",
      "Mark Randolph",
      "Reed Hastings",
      "Yoav Zilbershtein",
      "Dobi Frances",
      "Zohar Levkovitz",
      "Avi Eyal",
      "Micky Malka",
      "Einat Guez",
      "Yossi Zayger",
      "Adi Eyal",
      "Paul Graham",
      "John D. Rockefeller",
      "Tim Cook",
      "Roy Mann",
      "Eran Zinman",
      "Adam Singolda",
      "Dietmar Hopp",
      "Hasso Plattner",
      "Hans Werner Hector",
      "Claus Wellenreuther",
      "Klaus Tschira",
      "Bob Miner",
      "Lawrence J. Ellison",
      "Stephen Hawking",
      "Eduardo Saverin",
      "Dustin Moskovitz",
      "Chris Hughes",
      "Ken Xie",
      "Michael Xie",
      "Gordon Bowker",
      "Jerry Baldwin",
      "Zev Siegl",
      "Shlomo Kramer",
      "Marius Nacht",
      "Gil Shwed",
      "Yuming Mao",
      "Rajiv Batra",
      "Gordon Moore",
      "Robert Noyce",
      "Moti Gutman",
      "Shay Basson",
      "Asi Levinger",
      "Giora Kaplan",
      "Nadav Abrahami",
      "Avishay Abrahami",
      "Yair Rotlevi",
      "Vladimir Tenev",
      "Baiju Bhatt",
      "Leroy Grumman",
      "Jack Northrop",
      "Allan Lockheed",
      "Glenn L. Martin",
      "Jonh Moody",
      "Harel Vizel",
    ],
  },
  {
    LegalandLaw: [
      "(IP)Intellectual Property",
      "Copyrights",
      "Trademarks",
      "Patents",
      "Trade-Secrets",
      "IP Valuation",
      "IP Strategies",
      "Contract Laws",
      "Competition Laws",
      "Employment Laws",
      "Industries Regulations",
      "USPTO",
      "European Patent Office",
      "The Israeli Patent Authority",
    ],
    link: LEGAL_AND_LAW_ROUTE,
  },
  {
    BusinessDevelopment: [
      "Board of Directors",
      "Board of Advisors",
      "Business License Process in Israel",
      "Company Registration Process",
      "Business Plans",
      "Guiding Questions for Startups",
      "Core Commitments(Mission, Vision, Values)",
    ],
    link: BUSINESS_DEVELOPMENT,
  },
];
